#!/usr/bin/env bash
# Concatenate the JS layer into a single /script.js.
# No bundler, no minifier — the vendor files are already minified and each
# source file is an isolated IIFE, so plain concatenation is safe and keeps the
# Raspberry Pi deploy (server.js `publicFiles` allowlist) a one-file copy.
set -euo pipefail
cd "$(dirname "$0")"

OUT=script.js
{
  echo "/* GENERATED by build.sh — edit assets/js/*.js and vendor/*, then re-run. */"
  for f in \
    vendor/gsap.min.js \
    vendor/ScrollTrigger.min.js \
    vendor/ScrollSmoother.min.js \
    vendor/SplitText.min.js \
    vendor/CustomEase.min.js \
    assets/js/app.js \
    assets/js/motion.js
  do
    echo ""
    echo "/* ===== $f ===== */"
    cat "$f"
  done
} > "$OUT"

echo "built $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
node -c "$OUT" && echo "syntax ok"
